### PR TITLE
Adds CSS modules hot reloading

### PR DESCRIPTION
**Pull request by adri**
Integrates [CSS modules](https://github.com/css-modules/css-modules).

Uses `css-modules-require-hook` for server rendering and `css-loader`
for webpack integration.

Try changing `client/common/layout.css` or `client/components/App.css`.
Changes apply immediately and are persisted when reloading.

ultimate-reload-css

### CODE REVIEW

**Comment by glenjamin** [comment]
Awesome! Doesn't look like the extract text plugin is enabled - and some of those new dependencies aren't used?

How does this do server CSS rendering? If it doesn't yet, we can just remove those bits for now and get the client bits merged.

**Comment by adri** [comment]
I'd put the extract text plugin in a (different) webpack config for production since it is not really needed while developing. Would you include it in the current config? 

Those postcss dependencies can be deleted when the compatibility issues with postcss 5.x are resolved, see [this issue in the bottom](https://github.com/css-modules/css-modules-require-hook/issues/38).

> How does this do server CSS rendering?

The `css-modules-require-hook` renders the CSS and resolves all CSS imports (`composes`) when the server renders the page. This ensures the correct CSS class names are used in the `className` props.  It however does not generate a CSS file. For that we would have to add the  extract text plugin.

**Comment by glenjamin** [comment]
ah, i see they're peer dependencies of `css-modules-require-hook`.

I'd been using `npm@3` with this project, so any peer dependencies do need to be explicitly specified -  what you have at the moment is correct.

Is there any way to get the server-side `css-modules` generated CSS into a server handled route? Is it possible to get the `style-loader` to play nice with a server rendered CSS file?

I'll merge the code you've done here - but I think to be able to claim "Server-side css-modules hot reloading" we would want the CSS to work if JavaScript was disabled on the client (eg. on initial load before JS kicks in).

**Comment by adri** [comment]
Mh not sure if I understand. Afaik it is either "hot loading" or "extract styles to file". Did you see this every working together?

I could provide a `webpack.production.config.js` file which generates a style file using the extract text plugin if you like.

**Comment by glenjamin** [comment]
The distinction is that currently if you disable JS, and load the server-rendered page - you get exactly what you would get on the client. IMO this is true server-side reloading.

With this change, you don't actually get the CSS from the server render - only on the client.

Therefore we have hot reloading client-side CSS. But we don't yet have hot reloading server-side CSS. 

The require hook stuff is good because it keeps the checksum correct, but this doesn't give us what I would call server-side CSS. I've never seen this working, and I don't think this example needs to show it - just that we shouldn't include that bullet point on the readme.

Providing an example of how to get a proper production build would be good - but not essential and not related to this PR directly.

**Comment by adri** [comment]
Got it :) I removed the line.

**Comment by glenjamin** [comment]
Wrong line! i'll merge and fix the readme myself - no point in me making you do it!

**Comment by glenjamin** [comment]
Cheers for submitting this - I've also added your GIF to the README.

**Comment by adri** [comment]
Oh. Sorry about that! Thanks for merging.

**Pull request merged**
